<x-layout title="Funnel overview"><section class="container section">
    <div class="eyebrow">SELLERBOOST / ADMIN</div><div class="section-heading"><div><h1 class="page-title">The bigger <em>picture.</em></h1><p class="lede">Real activity. A clearer view of your funnel.</p></div><form method="POST" action="{{ route('admin.logout') }}">@csrf<button class="button outline">Sign out ↗</button></form></div>
    <div class="dashboard-meta"><span class="pill">ALL TIME</span><span>{{ config('funnel.mock_stripe') ? 'Mock payments enabled' : 'Stripe test payments' }}</span><span>Paid path {{ config('funnel.paid_enabled') ? 'open' : 'paused' }}</span></div>
    <div class="metric-grid">@foreach(['visitor' => 'Unique visitors', 'signup' => 'Free signups', 'checkout' => 'Checkout starts', 'paid' => 'Paid conversions'] as $key => $label)<article class="panel metric"><span>{{ $label }}</span><strong>{{ number_format($metrics[$key] ?? 0) }}</strong><small>{{ $key === 'visitor' ? 'Browser assignments' : 'Once per visitor' }}</small></article>@endforeach</div>
    <div class="section-heading compact"><div><div class="eyebrow">THE LANDING EXPERIMENT</div><h2>Two ways to say hello.</h2></div><p>Random 50/50 assignment · 30-day cookie<br>Directional data, not a significance test.</p></div>
    <div class="kit-grid">@foreach($variants as $variant => $counts)@php($visitors = (int) ($counts['visitor'] ?? 0))<article class="panel variant-card"><span class="pill">VARIANT {{ $variant }}</span><h3>{{ $variant === 'A' ? 'Great products. Great growth.' : 'Less guesswork. More customers.' }}</h3><div class="variant-stats"><div><strong>{{ $visitors }}</strong><span>visitors</span></div><div><strong>{{ number_format($visitors ? ($counts['signup'] ?? 0) / $visitors * 100 : 0, 1) }}%</strong><span>signup rate</span></div><div><strong>{{ number_format($visitors ? ($counts['paid'] ?? 0) / $visitors * 100 : 0, 1) }}%</strong><span>paid rate</span></div></div><p class="form-note">{{ $counts['signup'] ?? 0 }} signups · {{ $counts['paid'] ?? 0 }} paid visitors</p></article>@endforeach</div>
    <div class="panel assignments-panel"><div class="card-top"><h2>Recent assignments</h2><span class="pill">{{ $assignments->total() }} TOTAL</span></div><div class="table-scroll"><table><thead><tr><th>Visitor</th><th>Variant</th><th>Journey</th><th>Events</th><th>Assigned (UTC)</th></tr></thead><tbody>@forelse($assignments as $assignment)<tr><td><code title="{{ $assignment->id }}">{{ substr($assignment->id, 0, 8) }}</code></td><td><span class="variant-badge">{{ $assignment->variant }}</span></td><td>{{ $assignment->lead?->paid_at ? 'Growth Kit unlocked' : ($assignment->lead ? 'Free workspace' : 'Exploring') }}</td><td>{{ $assignment->events_count }}</td><td>{{ $assignment->created_at->format('M j, Y · H:i') }}</td></tr>@empty<tr><td colspan="5" class="empty-state">Your funnel is ready. Open the landing page to record the first visit.</td></tr>@endforelse</tbody></table></div><div class="pagination">@if($assignments->previousPageUrl())<a href="{{ $assignments->previousPageUrl() }}">← Previous</a>@endif<span>Page {{ $assignments->currentPage() }} of {{ $assignments->lastPage() }}</span>@if($assignments->nextPageUrl())<a href="{{ $assignments->nextPageUrl() }}">Next →</a>@endif</div></div>
    <p class="form-note">Visitors are browser assignments, not verified people. Cookie deletion creates a new visitor. All payments are test/demo conversions; these are not revenue figures.</p>
</section></x-layout>
